### ISSUE TITLE
Garbled on Windows CMD

### ISSUE THREAD

**Issue by kice** [ultralist/ultralist#69] opened 2017-06-21 01:11 UTC
![](https://ooo.0o0.ooo/2017/06/21/5949c6d3a169d.png)

As shown above, there are some issues with Win CMD. 

There might be a useful issue that can help solve this problem. https://github.com/sirupsen/logrus/issues/496

By the way, I only can get readable output on Git Bash with no color output.

**Comment by gammons** [comment] 2017-06-21 18:43
@kice hmmm, what shell is this?  Does it support any colors?

**Comment by gammons** [comment] 2017-07-07 12:32
haven't heard back for a while, so closing.  if you can provide more info we can re-open.

**Comment by matjojo** [comment] 2019-03-04 14:23
Same problem for me, on windows 10, version: 0.8.1

The colour does work on the page that comes up when you just call todolist, but it garbles text just like @kice had on listing todos:
![cmd_2019-03-04 - 1551709406 - 00000144](https://user-images.githubusercontent.com/8158314/53739209-7d9afc80-3e91-11e9-9f45-2e392bd85c75.png)

**Comment by gammons** [comment] 2019-03-08 18:39
Dupe of #143

**Closed by gammons** 2019-03-08 18:39 UTC
