### ISSUE TITLE
Does not display characters correctly

### ISSUE THREAD

**Issue by higoorc** [ultralist/ultralist#171] opened 2019-03-19 12:29 UTC
![image](https://user-images.githubusercontent.com/42069752/54605871-350f4180-4a42-11e9-9ce7-3abe60813320.png)

I tried just in Windows x64, with .exe installer.
I did something wrong? Maybe If its necessary I can try with Go.

**Comment by gammons** [comment] 2019-03-19 12:45
dupe of #143 

@higoorc we'll have the ability to disable color support in the next week or so, pending the merge of #168.  It's becoming a high priority since we've heard a lot of complaints about this.

**Closed** 2019-03-19 12:46 UTC
